owner-repo: &owner-repo
  owner-repo: palantir/go-nobadfuncs

version: 2.1

orbs:
  go: palantir/go@0.0.15
  godel: palantir/godel@0.0.15

workflows:
  version: 2
  verify-test:
    jobs:
      - godel/verify:
          name: verify
          executor:
            name: go/golang
            version: 1.13.4
            <<: *owner-repo
      - godel/test:
          name: test-go-1.13
          executor:
            name: go/golang
            version: 1.13.4
            <<: *owner-repo
      - godel/test:
          name: test-go-1.12
          executor:
            name: go/golang
            version: 1.12.13
            <<: *owner-repo
