owner-repo: &owner-repo
  owner-repo: palantir/go-nobadfuncs

version: 2.1

orbs:
  go: palantir/go@0.0.15
  godel: palantir/godel@0.0.15

workflows:
  version: 2
  verify-test:
    jobs:
      - godel/verify:
          name: verify
          executor:
            name: go/golang
            version: "1.15"
            <<: *owner-repo
      - godel/test:
          name: test-go-1.15
          executor:
            name: go/golang
            version: "1.15"
            <<: *owner-repo
      - godel/test:
          name: test-go-1.14
          executor:
            name: go/golang
            version: 1.14.7
            <<: *owner-repo
